apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-app

resources:
  - namespace.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - worker-deployment.yaml
  - result-deployment.yaml
  - result-service.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - ingress.yaml
